[azure_blob_storage]
storage_resource_url="https://deviotblob.blob.core.windows.net/?"
token = "sv=2021-12-02&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2026-05-30T01:35:06Z&st=2023-03-25T17:35:06Z&spr=https&sig=nQESohCzUVgz5D7MZeG5jXAoYljjSTUZov14000cVUE%3D"
